version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6-bullseye-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Dependencies
          command: npm run api-test
      - run:
          name: Run tests
          command: npm run test
